on:
  push:
    branches:
    - main
    - release/*
jobs:
  sendMail:
    runs-on: ubuntu-22.04
    steps:
    - name: Send email
      uses: devellany/send-mail@v1.0.2
      with:
       host: smtp.google.com
       account: ${{secrets.ACCOUNT}}
       password: ${{secrets.MAIL_PASSWORD}}
       sender: devellany
       from: "examencloudsystemen.redouane@gmail.com"
       to: "examencloudsystemen.redouane@gmail.com"
       subject: mail title.
       body: body:file://linesofcode.txt
       
       
  
